### ISSUE TITLE
Δημιουργία Live CD

### ISSUE THREAD

**Issue by falexakos** [itminedu/edu_distributions#3]
Πιστεύω ότι θα εξυπηρετούσε πολύ η ύπαρξη του αντίστοιχου Live-CD (iso image) ώστε να μπορούμε να δοκιμάζουμε την αντίστοιχη διανομή, χωρίς να χρειάζεται να αντικαθιστούμε το Λ/Σ που ενδεχομένως υπάρχει ήδη στα PCs κάποιου σχολείου.
Για το ΚΕΠΛΗΝΕΤ Καρδίτσας,
Φ. Αλεξάκος

**Comment by panosgeorgak** [comment]
Αγαπητέ 

Μπορεις να χρησιμοποιήσεις το VM image πλατφόρμας virtual box για δοκιμή των διανομών.

**Comment by falexakos** [comment]
Σε κάποια μηχανήματα (π.χ. με μικρό δίσκο ή με 1GB RAM) είναι απλώς ... αδιανόητο να εγκαταστήσεις και να εκτελέσεις π.χ. το VirtualBox. Χώρια που η ίδια η εγκατάσταση **και** παίρνει πιο πολύ χρόνο απ' το να εκκινήσεις από DVD και να δεις σε 10' πόσο αξιοπρεπώς τρέχει η Χ διανομή στο εν λόγω μηχάνημα **και** η ταχύτητα που βλέπεις στη VM, λίγη σχέση έχει με την πραγματικότητα (είναι σαφώς πιο αργό).

**Comment by panosgeorgak** [comment]
Σε τόσο παλιά μηχανήματα δεν έχει νόημα να εκτελεσθεί διανομή με σύγχρονο
περιβάλλον X-Windows που περιλαμβάνει προχωρημένα εφέ παρουσίασης.
Εχουμε ετοιμάσει έκδοση Ubuntu 16.04 Xenial που διαθέτει και live
λειτουργία η οποία έχει εγκατασταθεί σε PC διαγωνισμού του νοτίου αιγαίου.
Η διανομή αυτή θα είναι σύντομα διαθέσιμη και σε download links
Μέχρι τότε μπορείς να δοκιμασεις το 32bit VM image που είναι optimized για
παλιά μηχανήματα σε προσωπικό σου υπολογιστή και αν σου κάνει να κάνεις το
ISO install στο παλιό μηχάνημα.

2017-03-31 10:57 GMT+03:00 falexakos <notifications@github.com>:
