### ISSUE TITLE
Λογαριασμός χρήστη root

### ISSUE THREAD

**Issue by gskountzis** [itminedu/edu_distributions#5]
Συγχαρητήρια για την εξαιρετική δουλειά.
Προσπαθώ να κάνω κοινή χρήση φακέλων μεταξύ host και guest στις εικονικές μηχανές OSElementary_VM64.tar.gz και  customDistros_OpenSourcePreschool_VM-Preschool64.tar.gz αλλά από ότι είδα σε σχετικά site στο διαδίκτυο χρειάζομαι root δικαιώματα. Έχω καταφέρει να  κάνω χρήση του "Προχείρου" και USB 3 δυνατότητες αλλά θα ήθελα να υλοποιήσω και την παραπάνω κοινή χρήση φακέλων.
Είναι δυνατόν να έχουμε το password του root χρήστη ή μπορεί να γίνει και με άλλο τρόπο.
Ευχαριστώ
Καλή Δύναμη 
Γ. Σκουντζής, Δάσκαλος

**Comment by panosgeorgak** [comment]
Αγαπητέ

Ο κωδικός του root ειναι csteacher

Ευχαριστούμε

**Comment by gskountzis** [comment]
Ευχαριστώ,
δούλεψε και η κοινή χρήση 👍
