### ISSUE TITLE
Πρόβλημα με το pdf:  οδηγός-εγκατάστασης-elementary.pdf

### ISSUE THREAD

**Issue by gskountzis** [itminedu/edu_distributions#8]
Δεν έγινε σωστή μετατροπή του οδηγού σε pdf .

**Comment by panosgeorgak** [comment]
Αγαπητέ κ. Σκουντζή

Μπορείτε να μας δώσετε επιπλέον λεπτομέρειες του προβλήματος.

Με εκτίμηση

**Comment by gskountzis** [comment]
Δείτε σελ. 19, 21, 22, 23, 31, 32 κ.α του επισυναπτόμενου
[οδηγός-εγκατάστασης-elementary.pdf](https://github.com/itminedu/edu_distributions/files/975817/-.-elementary.pdf)
